name = "laifen-calendar-worker"
main = "src/index.ts"
compatibility_date = "2025-06-09"

[vars]
FEISHU_APP_ID = "cli_aaad3bb745799bd8"
FEISHU_APP_SECRET = "FWOViZgDEXaNhygLwfLmFgk0xW1a2CKU"
BITABLE_APP_TOKEN = "RgFqbx0bxa0l1DsQyOccbe7mn7g"
TABLE_ID = "tbleaarDLgkbDhcH"
